### ISSUE TITLE
Random error for IllegalStateException in Pycharm with WSL. Can't access sourcery.log

### ISSUE THREAD

**Issue by Se7enSquared** [sourcery-ai/sourcery#293]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
In Pycharm a few times I suddently get a "IDE Error" and it says it's caused by sourcery

### Debug Information

Pycharm Pro  Latest version project stored in WSL2 ubuntu

Sourcery Version:   0.12.11

Operating system and Version:  Windows 11 using WSL2

```
java.lang.IllegalStateException: Missing header Content-Length in input "--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\util\exception.py", line 77, in wrapped
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\engine\refactor.py", line 770, in _run_cached_standalone_scans
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\engine\standalone_scanners.py", line 57, in run_standalone_scans
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\engine\standalone_scanners.py", line 84, in run_scanner
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\engine\standalone_scanners.py", line 212, in _run_split_standalone_scanners
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\nodes.py", line 150, in run
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\runner.py", line 181, in run
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\runner.py", line 212, in _run_visitors
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\runner.py", line 212, in _run_visitors
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\runner.py", line 234, in _run_visitors
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\walker.py", line 131, in walk
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\walker.py", line 131, in walk
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\walker.py", line 135, in walk
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\analysis\statement_conditions.py", line 129, in leave_if
  File "C:\Users\HEATHE~1\AppData\Roaming\JETBRA~1\PYCHAR~1.2\plugins\sourcery\SOURCE~1\install\win\sourcery\ast\nodes.py", line 702, in __getitem__
IndexError: tuple index out of range

"
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:91)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Hellebore** [comment]
@Se7enSquared  Thanks for raising this - is it associated with viewing certain files or taking any specific actions in the IDE?

**Comment by Se7enSquared** [comment]
> @Se7enSquared  Thanks for raising this - is it associated with viewing certain files or taking any specific actions in the IDE?

It went away for now. But I think it has something to do with WSL Maybe? I'll let you know if it comes back

**Comment by Se7enSquared** [comment]
This issue has never come back. I think it could be closed. I think it was due to an issue on my end
