### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work, on Ubuntu 14.04

### ISSUE THREAD

**Issue by nnikolic72** [sourcery-ai/sourcery#316]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description

When starting VS Code that is running on Ubuntu 14.04 I am getting the error (pasted below).

Kindly note that Sorcery was working fine for months in this config, until one update (a month or two ago) that broke the compatibility. 

### Code snippet that reproduces issue
This is the Sourcery extension log I am getting:
```
[Info  - 2:01:23 AM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/__main__.py", line 8, in <module>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/binary/command_line_interface.py", line 35, in <module binary.command_line_interface>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/binary/hub_server.py", line 12, in <module binary.hub_server>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/hub/app.py", line 31, in <module hub.app>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/rules/proposers.py", line 10, in <module sourcery.rules.proposers>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/rules/private/comments/dsl/avoid_builtin_shadow.py", line 3, in <module sourcery.rules.private.comments.dsl.avoid_builtin_shadow>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/conditions/__init__.py", line 11, in <module sourcery.conditions>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/conditions/metric_conditions.py", line 7, in <module sourcery.conditions.metric_conditions>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/metrics/peak_working_memory.py", line 14, in <module sourcery.metrics.peak_working_memory>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/analysis/statement_conditions.py", line 4, in <module sourcery.analysis.statement_conditions>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/analysis/logic_solver.py", line 10, in <module sourcery.analysis.logic_solver>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/sourcery/analysis/boolean_algebra.py", line 13, in <module sourcery.analysis.boolean_algebra>
  File "/home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/pysat/solvers.py", line 157, in <module pysat.solvers>
ImportError: /home/x-nnikolic/.vscode-server/extensions/sourcery.sourcery-1.0.3/sourcery_binaries/install/linux/pysolvers.so: symbol _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
libgcc_s.so.1 must be installed for pthread_cancel to work
```

### Debug Information

IDE Version: 
VS Code 1.74.3

Sourcery Version: 
v1.0.3

Operating system and Version:
Ubuntu 14.04

**Comment by bm424** [comment]
Hi @nnikolic72, thanks for reporting this. I've tried to see if we can implement an easy fix, but I don't think it's going to be straightforward. 

I'm sorry that Sourcery has stopped working for you, but Ubuntu 14 is out of long-term support and as far as I am aware we haven't had reports of errors for more recent versions of Ubuntu, so I'm afraid we're not going to dedicate time to fixing this.

**Comment by Silvrbckw** [comment]
How do I know when Im installed. It keeps asking me to program Powershell 7. I used the winget method. Am I all set ? Can someone help me. Im new on the job. Hoping I can find a mentor . my email address is silverbackgodx@gmail.com . Am I allowed to leave my number?
