### ISSUE TITLE
could not start Sourcery service java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by hanyce** [sourcery-ai/sourcery#340]
it seem i have on file black, how can i install to this directory?
'C:\\Users\\hannes.zhang\\AppData\\Local\\black\\black\\Cache\\23.3.0\\Grammar3.10.11.final.0.pickle'

### Code snippet that reproduces issue

```python

```

### Debug Information
Traceback (most recent call last):
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\__main__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\binary\command_line_interface.py", line 32, in <module binary.command_line_interface>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\binary\auth.py", line 11, in <module binary.auth>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\binary\util.py", line 15, in <module binary.util>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\sourcery\engine\refactorings.py", line 31, in <module sourcery.engine.refactorings>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\sourcery\code\code_section.py", line 8, in <module sourcery.code.code_section>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\sourcery\code\skip_comments.py", line 6, in <module sourcery.code.skip_comments>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\sourcery\code\source_unparser.py", line 9, in <module sourcery.code.source_unparser>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\black\__init__.py", line 38, in <module black>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\black\comments.py", line 12, in <module black.comments>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\black\nodes.py", line 25, in <module black.nodes>
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\blib2to3\pygram.py", line 181, in initialize
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\blib2to3\pgen2\driver.py", line 305, in load_packaged_grammar
  File "C:\Users\hannes.zhang\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\sourcery\sourcery_binaries\install\win\pkgutil.py", line 639, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hannes.zhang\\AppData\\Local\\black\\black\\Cache\\23.3.0\\Grammar3.10.11.final.0.pickle'

IDE Version: 
PyCharm Community Edition 2022.1

Sourcery Version: 
Sourcery 1.2.0

Operating system and Version:
windows 10

**Comment by hanyce** [comment]
hi;
I have just solved the problem.
I upgraded pycharm from 2022.1 to 2022.2 and it can be used normally.

**Comment by ruancomelli** [comment]
Hello, @hanyce! Sorry for the late response - we're glad you were able to solve it by upgrading PyCharm!
Please let us know if you run into any other issues again :smile:
